%% FUNCTION THAT RETURNS A CELL OF POSSIBLE STATES OVER WHICH
% THE PROGRAM CAN ITERATE

function states = get_possible_states(state)

states = { ... ALL OUTCOMES WHERE MINZOO IS MIN OFFER
           tmp_state(1,4),...
           tmp_state(1,5),...
           tmp_state(1,6),...
           tmp_state(2,4),...
           tmp_state(2,5),...
           tmp_state(2,6),...
           tmp_state(3,4),...
           tmp_state(3,5),...
           tmp_state(3,6),...
           ... ALL OUTCOMES WHERE MINZOO IS MAX OFFER
           tmp_state(4,1),...
           tmp_state(4,2),...
           tmp_state(4,3),...
           tmp_state(5,1),...
           tmp_state(5,2),...
           tmp_state(5,3),...
           tmp_state(6,1),...
           tmp_state(6,2),...
           tmp_state(6,3)...
          };
    
function new_state = tmp_state(minzoo,maxzoo)
    new_state = state;
    new_state.minzoo = minzoo;
    new_state.maxzoo = maxzoo;
    new_state.c = state.c - 1;
    new_state.lookahead = state.lookahead - 1;
end
end